version: '3.7'
services:

  minio1:
    build:
      context: .
    ports:
      - "9091:9000"
    restart: always
    volumes:
      - "./policy/:/policy/"
      - "./data/minio1/1/:/data/minio1"
      - "./data/minio1/2/:/data/minio2"
      - "./data/minio1/3/:/data/minio3"
      - "./data/minio1/4/:/data/minio4"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DISK_USAGE_CRAWL_DELAY: 30
    command: server /data/minio{1...4}/

  minio2:
    build:
      context: .
    ports:
      - "9092:9000"
    restart: always
    volumes:
      - "./data/minio2/1/:/data/minio1"
      - "./data/minio2/2/:/data/minio2"
      - "./data/minio2/3/:/data/minio3"
      - "./data/minio2/4/:/data/minio4"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_DISK_USAGE_CRAWL_DELAY: 30
    command: server /data/minio{1...4}/

  mc:
    image: minio/mc
    volumes:
      - "./policy/:/policy/"
    depends_on:
      - minio1
      - minio2
    entrypoint: >
      /bin/sh -c "
      sleep 10s;
      mc alias set $MINIO_ALIAS_1 http://minio1:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;
      mc alias set $MINIO_ALIAS_2 http://minio2:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY;
      mc mb --ignore-existing $MINIO_ALIAS_1/$MINIO_BUCKET;
      mc version enable $MINIO_ALIAS_1/$MINIO_BUCKET;
      mc mb --ignore-existing $MINIO_ALIAS_2/$MINIO_BUCKET;
      mc version enable $MINIO_ALIAS_2/$MINIO_BUCKET;
      mc admin policy add $MINIO_ALIAS_1 replpolicy /policy/policy1.json;
      mc admin policy add $MINIO_ALIAS_2 replpolicy /policy/policy2.json;
      mc admin user add $MINIO_ALIAS_2 repluser repluserpwd;
      mc admin policy set $MINIO_ALIAS_2 replpolicy user=repluser;
      mc admin bucket remote add $MINIO_ALIAS_1/$MINIO_BUCKET http://repluser:repluserpwd@$MINIO_ALIAS_2:9000/$MINIO_BUCKET --service "replication";
      mc replicate add $MINIO_ALIAS_1/$MINIO_BUCKET --remote-bucket $MINIO_BUCKET --priority 1 --arn arn:minio:replication::bd77145eb97a40c0cd388cce572b8a90920f2b0809e5e3421f3a7a9908941929:terminal;
      exit 0;
      "